### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thompsonemerson** [thompsonemerson/zoomove#1]
- [ ] Support Touch
- [ ] Hover zoom mini-modal
- [ ] Scroll zoom control
- [ ] Height dynamics

**Comment by alisonmonteiro** [comment]
The "Popup zoom style" could be based on [fat/zoom.js](http://fat.github.io/zoom.js/), I think. What do you think?

**Comment by thompsonemerson** [comment]
Yeah... nice example @alisonmonteiro! but I think this fits into a new "Click modal style".

**Comment by alisonmonteiro** [comment]
Good idea! :+1:
