### ISSUE TITLE
Opção de Alterar o Zoom

### ISSUE THREAD

**Issue by macielcr7** [thompsonemerson/zoomove#2]
aquele controle de zoom.. para alterar.. a escala... parecido com o do google maps... transparente...

**Comment by thompsonemerson** [comment]
massa, se quiser mandar PR fica a vontade... ;)

**Comment by thompsonemerson** [comment]
@macielcr7  qualquer coisa acompanha lá no [Roadmap](https://github.com/thompsonemerson/zoomove/issues/1), montei uma lista de futuras implementações lá.

**Comment by macielcr7** [comment]
blza...
