### ISSUE TITLE
Transparent images do not mask the figure content

### ISSUE THREAD

**Issue by sunnywalker** [thompsonemerson/zoomove#5]
Transparent images (such as the zoomove logo SVG) do not mask out the figure's content. For example, in the demo, add another column with the zoomove logo SVG and you'll see the "loading" text showing through.

![screen shot 2016-05-16 at 11 08 17 am](https://cloud.githubusercontent.com/assets/187270/15303989/83b8016e-1b56-11e6-81dc-9f730b52acec.png)

~~~html
<div class="column">
  <div class="item">
    <figure class="zoo-item" zoo-image="logo_zoomove.svg">Loading...</figure>
  </div>
  <small class="text-center">Image 4</small>
</div>
~~~

**Comment by sunnywalker** [comment]
I've added a simple way to mask along with quite a few other features in pull request #6 .

**Comment by thompsonemerson** [comment]
Hi @sunnywalker,
Your pull request (#6) have conflicts, corrects there for us!
