### ISSUE TITLE
Zoomove only works if figure container has fixed height

### ISSUE THREAD

**Issue by sbrin** [thompsonemerson/zoomove#8]
Zoomove only works if figure container has fixed height. Can you make it work with any (unknown) image height?

**Comment by thompsonemerson** [comment]
Hi @sbrin, in the new version this problem will be fixed, the height will be dynamic.

**Comment by hmdadou** [comment]
My solution for this problem was like this create a wrapping div then add img inside the figure tag.

`<div class="img-holder">
    <figure class="zoo-item" data-zoo-image="your image path here">
        <img class="hiddenimg img-responsive" src="your image path here">
    </figure>
</div>`

The css
`.img-holder {
    position: relative;
    display: block;
    text-align: center;
    overflow: hidden;
}
.zoo-item .zoo-img {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    transition: transform 0.5s ease-out;
}
`
notice I added position:absolute to the original css class  .zoo-item .zoo-img.
I also added img-responsive to image not necessary if you are not using bootstrap.

**Comment by 4pixels** [comment]
Thanks hmdadou for your solution. I had to change it slightly. I don't know if that's anything with Bootstrap, I wouldn't have thought so. 

HTML is as yours.

CCS 
- .zoo-item changed to position: relative; 
- and I got rid of the original display: flex;
- .zoo-img became one selector. 

.zoo-item {
	position: relative;
	width: 100%;
	height: 100%;
	overflow: hidden;
	transition: all 150ms linear;
	align-items: center;
	justify-content: center;
}

.zoo-img {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-repeat: no-repeat;
	background-position: center;
	background-size: cover;
	transition: transform 0.5s ease-out;
}

.img-holder {
	position: relative;
	display: block;
	text-align: center;
	overflow: hidden;
}

.hiddenimg {
	visibility: hidden;
}

**Comment by thompsonemerson** [comment]
compatible from the latest version ;)
